### ISSUE TITLE
Link brutto

### ISSUE THREAD

**Issue by alcir** [linuxhubit/linuxhub.it#19]
https://github.com/linuxhubit/linuxhub.it/blob/fdc8ec10fafc91a42cd77fb557498caa3f306466/_includes/footer.html#L74

Questo link a linuxpeople.org è da togliere?

**Comment by PsykeDady** [comment]
grazie per la segnalazione! si dobbiamo toglierlo

**Comment by PsykeDady** [comment]
rimosso con commit c3d0cc786856ef2554dc3a6135c71b4aef98cdd3
