### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by gianfrus** [linuxhubit/linuxhub.it#24]
Salve, il link a linuxpeople.org inserito nel canale Telegram porta a un sito di mass-redirection verso le solite pagine truffaldino/pubblicitarie/acchiappababbei.

**Comment by PsykeDady** [comment]
purtroppo linuxpeople.org non esiste più 

abbiamo chiuso il progetto, ora abbiamo solo linuxhub.it 
ora vedo un attimo di rimuovere qualunque riferimento

**Comment by PsykeDady** [comment]
Grazie della segnalazione! se trovi altri riferimenti diccelo pure su telegram stesso così leggo prima
